### ISSUE TITLE
no input device after loading

### ISSUE THREAD

**Issue by erazor83** [ArhiChief/eleduino_ts#2]
Hi there!

Just tried your kernelmodule but it seems it does not create any device files.

<pre>
[ 4896.169597] eleduino_ts: v0.0.1.Eleduino tft 7inch display. USB touchscreen driver.
RPI - Test 1 input # cat /proc/bus/input/devices 
RPI - Test 1 input # 
</pre>

Did I miss anything?

**Comment by ArhiChief** [comment]
Hello.
My module is just in develop stage. Please look at fork here:
https://github.com/noonien-d/eleduino_ts. Looks like, that this is working fork of my module.

**Comment by erazor83** [comment]
Yes, the fork works!
