### ISSUE TITLE
Multitouch?

### ISSUE THREAD

**Issue by erazor83** [ArhiChief/eleduino_ts#3]
I'm wondering if it already supports multitouch?

The hardware seems to support it.

**Comment by ArhiChief** [comment]
It's in my plans, but I have no time now for develop.

**Comment by erazor83** [comment]
is there any info on where to start? I'd invest some time... I'll have a look into the eleduino_ts.c later this day.

**Comment by ArhiChief** [comment]
you can find more info inside drivers/input/touchscreen/edt-ft5x06.c. I use it to make manipulations.

**Comment by gusevargas** [comment]
Could anyone please, point me in the direction of a tutorial, on how to implement this 7" driver into the Raspberry new OS Jessie. Although all the driver files are available to download, there is no instructions, nor any detail explanation how to implement these files into the RPI2. 
anyone that could provide any help, it would be very much appreciated....

**Comment by ArhiChief** [comment]
@gusevargas. Hello, thank you for question.

Look into **README.md**, sections **Building** and **Installation** in master branch of repository.

To add support of touchscreen to your RPi, you need to build kernel module, put build result into **/usr/lib/modules/** on your RaspberryPi. I still can't find way how to make it works at Linux sturtup, so, you need to execute `# echo -n '0eef 0005' > /sys/bus/usb/drivers/eleduino_ts/new_id` on your RaspberryPi console.
